
#ifndef iotelic_keystorage_slots_H
#define iotelic_keystorage_slots_H

#define KEY_SLOT_STD_DATA_SIZE (381)  // Max data size of standard slot
#define KEY_SLOT_EXT_DATA_SIZE (1533) // Max data size of extended slot

typedef enum {
    KEY_SLOT_STD_OTP_0,
    KEY_SLOT_STD_OTP_1,
    KEY_SLOT_STD_OTP_2,
    KEY_SLOT_STD_OTP_3,
    KEY_SLOT_STD_OTP_4,
    KEY_SLOT_STD_OTP_5,
    KEY_SLOT_STD_OTP_6,
    KEY_SLOT_STD_OTP_7,
    KEY_SLOT_STD_OTP_8,
    KEY_SLOT_STD_OTP_9,
    KEY_SLOT_STD_OTP_10,
    KEY_SLOT_STD_OTP_11,
    KEY_SLOT_STD_OTP_12,
    KEY_SLOT_STD_OTP_13,
    KEY_SLOT_STD_OTP_14,
    KEY_SLOT_STD_OTP_MAX,
    KEY_SLOT_EXT_OTP_0,
    KEY_SLOT_OTP_MAX,
    KEY_SLOT_STD_MTP_0,
    KEY_SLOT_STD_MTP_1,
    KEY_SLOT_STD_MTP_2,
    KEY_SLOT_STD_MTP_3,
    KEY_SLOT_STD_MTP_4,
    KEY_SLOT_STD_MTP_5,
    KEY_SLOT_STD_MTP_6,
    KEY_SLOT_STD_MTP_7,
    KEY_SLOT_STD_MTP_8,
    KEY_SLOT_STD_MTP_9,
    KEY_SLOT_STD_MTP_10,
    KEY_SLOT_STD_MTP_11,
    KEY_SLOT_STD_MTP_12,
    KEY_SLOT_STD_MTP_13,
    KEY_SLOT_STD_MTP_14,
    KEY_SLOT_STD_MTP_MAX,
    KEY_SLOT_EXT_MTP_0,
    KEY_SLOT_MTP_MAX,
    KEY_SLOT_STD_TMP_0,
    KEY_SLOT_STD_TMP_1,
    KEY_SLOT_STD_TMP_2,
    KEY_SLOT_STD_TMP_3,
    KEY_SLOT_STD_TMP_4,
    KEY_SLOT_STD_TMP_5,
    KEY_SLOT_STD_TMP_6,
    KEY_SLOT_STD_TMP_MAX,
    KEY_SLOT_EXT_TMP_0,
    KEY_SLOT_TMP_MAX
} KEYSTORAGE_SLOT;

#endif // iotelic_keystorage_slots_H
