# VM configuration
MEMORY=3072
CPUS=2


$install_docker = <<-SHELL
    sudo dnf -y install dnf-plugins-core
    sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    sudo dnf install -y docker-ce docker-ce-cli containerd.io
    sudo systemctl enable --now docker
    sudo usermod -aG docker vagrant
SHELL


Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"

  # network settings
  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8081, host: 8081, protocol: "tcp"

  config.vm.provider "virtualbox" do |v|
    v.memory = MEMORY
    v.cpus = CPUS
  end

  config.vm.define "sandbox_f29" do |fc29|
    # box settings
  	fc29.vm.box = "fedora/29-cloud-base"
  	fc29.vm.box_version = "29.20181024.1"

  	# provision
  	fc29.vm.provision "shell", inline: $install_docker

  end

end
