# VM configuration
MEMORY=3072
CPUS=2


Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"

  # network settings
  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8081, host: 8081, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8000, host: 8000, protocol: "tcp"

  config.vm.provider "virtualbox" do |v|
    v.memory = MEMORY
    v.cpus = CPUS
  end

  config.vm.define "sandbox_f29" do |fc29|
    # box settings
  	fc29.vm.box = "dhrytsenko/fc29-docker"
  	fc29.vm.box_version = "0.1.0"

  end

end
